name: "build image"

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build_image.yml'
      - '.github/workflows/publish_image.yml'
      - '.github/workflows/image.yml'
      - 'Dockerfile'
      - 'vllm_ascend/**'

jobs:
  run-build:
    name: build
    secrets: inherit
    uses: ./.github/workflows/image.yml
    with:
      publish: false
