name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Free up disk space
      run: |
        echo "=================================="
        echo "Free up disk space on CI system"
        echo "=================================="
        
        echo "Listing top 100 largest packages (from large to small)"
        printf "Installed-Size\tPackage\n"
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n -r | head -n 100
        df -h
        
        echo "Removing large packages"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf /usr/share/php/
        sudo rm -rf /usr/local/graalvm/
        sudo rm -rf /usr/local/.ghcup/
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/lib/node_modules
        
        sudo rm -rf /opt/az
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /opt/hostedtoolcache/go
        sudo rm -rf /opt/hostedtoolcache/node
        
        sudo apt-get remove --purge -y '^aspnet.*'
        sudo apt-get remove --purge -y '^dotnet-.*'
        sudo apt-get remove --purge -y '^llvm-.*'
        sudo apt-get remove --purge -y 'php.*'
        sudo apt-get remove --purge -y '^mongodb-.*'
        sudo apt-get remove --purge -y snapd google-chrome-stable microsoft-edge-stable firefox
        sudo apt-get remove --purge -y azure-cli google-cloud-sdk mono-devel powershell libgl1-mesa-dri
        sudo apt-get autoremove --purge -y
        sudo apt-get clean
        
        df -h
    - name: Build - Set up QEMU
      uses: docker/setup-qemu-action@v2
      # https://github.com/docker/setup-qemu-action/issues/198
      with:
        image: tonistiigi/binfmt:qemu-v7.0.0-28

    - name: Build - Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build - Build the base image
      uses: docker/build-push-action@v3
      with:
        context: ${{ env.BASE_IMAGE_PATH }}
        tags: ${{ env.BASE_IMAGE_URL }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
