name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build - Set up QEMU
      if: ${{ inputs.build }}
      uses: docker/setup-qemu-action@v2

    - name: Build - Set up Docker Buildx
      if: ${{ inputs.build }}
      uses: docker/setup-buildx-action@v2

    - name: Build - Build the base image
      uses: docker/build-push-action@v3
      with:
        context: ${{ env.BASE_IMAGE_PATH }}
        tags: ${{ env.BASE_IMAGE_URL }}
        platforms: linux/amd64,linux/arm64
