name: Cleanup PR Body

on:
  workflow_call:
    inputs:
      append-body:
        required: false
        type: string
        default: ""

permissions:
  pull-requests: write

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.12'

      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.update({
                pull_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: context.payload.pull_request.body + '\n---\n' + "${{ inputs.append-body }}"
            })
