name: Cleanup PR Body

on:
  workflow_call:
    inputs:
      append-body:
        required: false
        type: string
        default: ""

permissions:
  pull-requests: write

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.update({
                pull_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: context.payload.pull_request.body + '\n---\n' + "${{ inputs.append-body }}"
            })
