name: Cleanup PR Body

on:
  pull_request_target:
    types: [opened, reopened, edited]

permissions:
  pull-requests: write

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout vllm-project/vllm repo
        uses: actions/checkout@v4
        with:
          repository: vllm-project/vllm
          ref: ${{ matrix.vllm_version }}
          path: ./vllm-empty

      - name: Get vLLM version
        working-directory: ./vllm-empty
        run: |
          VLLM_COMMIT=$(git rev-parse HEAD)
          echo "VLLM_COMMIT=https://github.com/vllm-project/vllm/commit/$VLLM_COMMIT" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.12'

      - name: Get vLLM release version
        run: |
          VLLM_VERSION=$(python3 docs/source/conf.py | jq .vllm_version | tr -d '"')
          echo "VLLM_VERSION=$VLLM_VERSION" >> $GITHUB_ENV

      - name: Update PR description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash .github/format_pr_body.sh "${{ github.event.number }}" "${{ env.VLLM_VERSION }}" "${{ env.VLLM_COMMIT }}"
