name: "publish image"

on:
  # Publish dev image for every commit
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build_image.yml'
      - '.github/workflows/publish_image.yml'
      - '.github/workflows/image.yml'
      - 'Dockerfile'
      - 'vllm_ascend/**'

jobs:
  run-build:
    name: publish
    secrets: inherit
    uses: ./.github/workflows/image.yml
    with:
      publish: true
